
name: proxmark3 # you probably want to 'snapcraft register <name>'
version: '1.111' # just for humans, typically '1.2+git' or '1.3.2'
summary: Automated snaps builds of the popular proxmark3 github repo # 79 char long summary
description: |
  This is a snap mirror of https://github.com/Proxmark/proxmark3 forked to my personal repo. 
  There are some firmware changes described in the commits. Mostly follows the parent project.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  client:
      command: bin/proxmark3client
      plugs: [home, network, network-bind, removable-media]

parts:
  client:
      source: ./client
      plugin: python
      build-packages:
          - gcc
          - lsb
          - perl 
          - libusb 
          - libusb-dev
          - libreadline
          - libreadline-dev
          - libreadline6
          - libqt4-dev
          - libpthread
          - make